name: flutter_cv2_camera
description: "A custom Flutter plugin that bridges the power of OpenCV in C++ with real-time camera access in Flutter. Designed to enable real-time image streaming, frame analysis, and snapshot capturing—perfect for AI/ML projects focused on computer vision."

version: 0.0.1
homepage: https://github.com/jamesadewara/flutter_cv2_camera/README.md
repository: https://github.com/jamesadewara/flutter_cv2_camera
issue_tracker: https://github.com/jamesadewara/flutter_cv2_camera/issues 
documentation:

environment:
  sdk: '>=3.7.0 <4.0.0' 
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      # android:
      #   ffiPlugin: true
      linux:
        ffiPlugin: true
      # windows:
      #   ffiPlugin: true
      # ios:
      #   ffiPlugin: true
      # macos:
      #   ffiPlugin: true

# Optional: Points to an example app
example:
  path: example