name: flutter_cv2_camera
description: "A Flutter plugin bridging OpenCV (C++) with real-time camera access for AI/ML computer vision projects. Supports live image streaming, analysis, and snapshots."

version: 0.0.1
homepage: https://github.com/jamesadewara/flutter_cv2_camera/README.md
repository: https://github.com/jamesadewara/flutter_cv2_camera
issue_tracker: https://github.com/jamesadewara/flutter_cv2_camera/issues 
documentation:

environment:
  sdk: '>=3.7.0 <4.0.0' 
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      # android:
      #   ffiPlugin: true
      linux:
        ffiPlugin: true
      # windows:
      #   ffiPlugin: true
      # ios:
      #   ffiPlugin: true
      # macos:
      #   ffiPlugin: true

# Optional: Points to an example app
example:
  path: example